default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: draft_development

test:
  <<: *default
  database: draft_test

production:
  <<: *default
  database: draft_production
  username: draft
  password: <%= ENV['DRAFT_DATABASE_PASSWORD'] %>
